Ceid Cpp Project 2020: EShop Class Reference
EShop Class Reference
Class implementing the e-shop.
#include <eshop.h>
Public Member Functions
EShop (string name)
Constructor of EShop.
EShop (string name, string owner, string email)
Constructor of EShop.
~EShop ()
The destructor of e-shop.
string getName ()
Get the name of the e-shop.
Owner * getOwner ()
Get the owner.
void addItem (Item *)
Add an Item to the e-shop.
void removeItem (Item *)
Remove an Item from the eshop if it exists.
Item * getItemById (size_t id)
Return an Item reference if the Item's ID is found in the e-shop.
void addBuyer (Buyer *)
Add a Buyer to the e-shop.
void removeBuyer (Buyer *)
Remove a Buyer from the eshop if it exists and clears their cart.
Buyer * getBuyerByEmail (string email)
Return a Buyer reference if the Buyer's email is found in the e-shop.
void updateItemStock (Item *, int)
Update an Item's stock.
vector< pair< string, int > > getCategories ()
Get the categories of Items that exist in the e-shop.
vector< pair< int, string > > getProductsInCategory (string)
Get the Items in a specific category.
void showProduct (Item *)
Shows the details of the specified product.
vector< vector< string > > checkStatus ()
Prints the status of the Buyers.
Private Member Functions
void setOwner (string name, string email)
Sets the name of the owner.
Private Attributes
string _name
Owner * _owner = nullptr
vector< Buyer * > _buyers
vector< Item * > _items
Detailed Description
Class implementing the e-shop.
This class implements the e-shop related functionality. There are two ways this class can be instantiated, either by passing the name of the e-shop, in which case we have to specify an owner later on or by passing the name and the email of the owner to the constructor. It also holds the manipulates the Items and the Buyers of the EShop.
Definition at line 22 of file eshop.h.
Constructor & Destructor Documentation
EShop() [1/2]
EShop::EShop (string name) explicit
Constructor of EShop.
Parameters
name <string> The name of the e-shop
Definition at line 7 of file eshop.cpp.
References _name, and _owner.
EShop() [2/2]
EShop::EShop (string name, string owner, string email)
Constructor of EShop.
Parameters
name <string> The name of the e-shop
owner <string> The name of the owner
email <string> The email of the owner
Definition at line 13 of file eshop.cpp.
References setOwner().
~EShop()
EShop::~EShop ()
The destructor of e-shop.
We require this to destroy any Item or Buyer objects created during execution
Definition at line 18 of file eshop.cpp.
References _buyers, _items, and _owner.
Member Function Documentation
addBuyer()
void EShop::addBuyer (Buyer * buyer)
Add a Buyer to the e-shop.
Checks if the Buyer already exists, if it does, throws and exception
Definition at line 75 of file eshop.cpp.
References _buyers, and User::getName().
Referenced by main().
addItem()
void EShop::addItem (Item * item)
Add an Item to the e-shop.
Checks if the Item already exists, if it does, throws and exception
Definition at line 41 of file eshop.cpp.
References _items, and Item::getName().
Referenced by main().
checkStatus()
vector< vector< string > > EShop::checkStatus ()
Prints the status of the Buyers.
Also returns a vector of vectors of strings with the information for each buyer
Returns
<vector<vector<string>>>
Definition at line 146 of file eshop.cpp.
References _buyers.
Referenced by Menu::showStatusMenu().
getBuyerByEmail()
Buyer * EShop::getBuyerByEmail (string email)
Return a Buyer reference if the Buyer's email is found in the e-shop.
Definition at line 100 of file eshop.cpp.
References _buyers.
Referenced by Menu::login(), main(), and Menu::showStatusMenu().
getCategories()
vector< pair< string, int > > EShop::getCategories ()
Get the categories of Items that exist in the e-shop.
Returns a vector of pairs consisting of the categories names and the number of products in each category.
Returns
<vector<pair<string, int>>>
Definition at line 120 of file eshop.cpp.
References _items.
Referenced by Menu::showBrowseMenu().
getItemById()
Item * EShop::getItemById (size_t id)
Return an Item reference if the Item's ID is found in the e-shop.
Definition at line 67 of file eshop.cpp.
References _items.
Referenced by main(), Menu::showCartMenu(), and Menu::showProductMenu().
getName()
string EShop::getName ()
Get the name of the e-shop.
Definition at line 161 of file eshop.cpp.
References _name.
Referenced by Menu::showOwnerMenu().
getOwner()
Owner * EShop::getOwner ()
Get the owner.
Definition at line 26 of file eshop.cpp.
References _owner.
Referenced by Menu::login().
getProductsInCategory()
vector< pair< int, string > > EShop::getProductsInCategory (string category)
Get the Items in a specific category.
Returns a vector of pairs consisting of the Item IDs and the name of each product
Returns
<vector<pair<int, string>>>
Definition at line 136 of file eshop.cpp.
References _items.
Referenced by Menu::showCategoryMenu().
removeBuyer()
void EShop::removeBuyer (Buyer * buyer)
Remove a Buyer from the eshop if it exists and clears their cart.
Definition at line 87 of file eshop.cpp.
References _buyers.
Referenced by main(), and Menu::showStatusMenu().
removeItem()
void EShop::removeItem (Item * item)
Remove an Item from the eshop if it exists.
Definition at line 55 of file eshop.cpp.
References _items.
Referenced by main().
setOwner()
void EShop::setOwner (string name, string email) private
Sets the name of the owner.
Definition at line 33 of file eshop.cpp.
References _owner.
Referenced by EShop().
showProduct()
void EShop::showProduct (Item * item)
Shows the details of the specified product.
Definition at line 114 of file eshop.cpp.
Referenced by main(), and Menu::showProductMenu().
updateItemStock()
void EShop::updateItemStock (Item * item, int delta)
Update an Item's stock.
Definition at line 108 of file eshop.cpp.
References Item::getStock(), and Item::setStock().
Referenced by Menu::showProductMenu().
Member Data Documentation
_buyers
vector<Buyer*> EShop::_buyers private
Definition at line 128 of file eshop.h.
Referenced by addBuyer(), checkStatus(), getBuyerByEmail(), removeBuyer(), and ~EShop().
_items
vector<Item*> EShop::_items private
Definition at line 129 of file eshop.h.
Referenced by addItem(), getCategories(), getItemById(), getProductsInCategory(), removeItem(), and ~EShop().
_name
string EShop::_name private
Definition at line 126 of file eshop.h.
Referenced by EShop(), and getName().
_owner
Owner* EShop::_owner = nullptr private
Definition at line 127 of file eshop.h.
Referenced by EShop(), getOwner(), setOwner(), and ~EShop().
The documentation for this class was generated from the following files:
src/eshop.h
src/eshop.cpp