Ceid Cpp Project 2020: User Class Reference
User Class Reference abstract
Base class for all users.
#include <user.h>
Public Member Functions
User (string name, string email)
Constructor for User, called by Owner and Buyer.
string getName ()
Get the Name of the user.
string getEmail ()
Get the Email of the user.
virtual bool isAdmin ()=0
Check if the user is an admin.
Private Member Functions
void setName (string name)
void setEmail (string email)
Private Attributes
string _name
string _email
Detailed Description
Base class for all users.
Base abstract class to subclassed by the Owner and Buyer specialized classes. Implements the common functions of setting the Name and the Email of the user.
Definition at line 15 of file user.h.
Constructor & Destructor Documentation
User()
User::User (string name, string email)
Constructor for User, called by Owner and Buyer.
Parameters
name string. The name of the user
email string. The email of the user
Definition at line 3 of file user.cpp.
References setEmail(), and setName().
Member Function Documentation
getEmail()
string User::getEmail ()
Get the Email of the user.
Parameters
none
Returns
string The user's email
Definition at line 19 of file user.cpp.
References _email.
Referenced by Menu::login(), Buyer::operator==(), Menu::showBuyerMenu(), and Menu::showOwnerMenu().
getName()
string User::getName ()
Get the Name of the user.
Parameters
none
Returns
string The user's name
Definition at line 13 of file user.cpp.
References _name.
Referenced by EShop::addBuyer(), Menu::login(), Buyer::operator==(), Menu::showBuyerMenu(), and Menu::showOwnerMenu().
isAdmin()
virtual bool User::isAdmin () pure virtual
Check if the user is an admin.
Virtual function implemented in the derivative classes
Parameters
none
Returns
bool True if the user is an owner, false otherwise.
Implemented in Buyer, and Owner.
Referenced by Menu::showBrowseMenu(), Menu::showProductMenu(), and Menu::showWelcome().
setEmail()
void User::setEmail (string email) private
Definition at line 16 of file user.cpp.
References _email.
Referenced by User().
setName()
void User::setName (string name) private
Definition at line 10 of file user.cpp.
References _name.
Referenced by User().
Member Data Documentation
_email
string User::_email private
Definition at line 57 of file user.h.
Referenced by getEmail(), and setEmail().
_name
string User::_name private
Definition at line 56 of file user.h.
Referenced by getName(), and setName().
The documentation for this class was generated from the following files:
src/user.h
src/user.cpp