Ceid Cpp Project 2020: Notebook Class Reference
Notebook Class Reference final
Class representing a Notebook.
#include <notebook.h>
Public Member Functions
Notebook (int subjects, int stock, double price, string name, string desc)
Constructor for Notebook.
void setSubjects (int subjects)
Set the number of subjects of the notebook.
int getSubjects ()
Get the Notebook's number of subjects.
void setId () override
Override of Item::setID()
string getDetails () override
Implements Item::getDetails() for Notebook.
Public Member Functions inherited from Item
Item (int stock, double price, string name, string desc)
Constructor for Item, called by the derivative classes.
virtual ~Item ()
Virtual destructor to force the reimplementation in the derivatives.
size_t getId ()
Get the ID of the item.
void setStock (int stock)
Set the stock of an item.
int getStock ()
Get the Item's stock.
void setPrice (double price)
Set the price of an item.
double getPrice ()
Get the Item's price.
void setName (string name)
Set the stock of an item.
string getName ()
Get the Item's name.
void setDescription (string desc)
Set the stock of an item.
string getDescription ()
Get the Item's description.
string getCategory ()
Get the Item's category (Pen, Pencil, Paper, Notebook)
string getBasicInfo ()
Get the Item's basic getBasicInfo.
void setId (size_t)
Set the Item's ID based on the hash.
void setCategory (string)
Set the Item's category.
operator std::string ()
Override the cast to std::string operator.
bool operator== (const Item &)
Override for the comparison operator.
Private Attributes
int _subjects
Detailed Description
Class representing a Notebook.
Definition at line 12 of file notebook.h.
Constructor & Destructor Documentation
Notebook()
Notebook::Notebook (int subjects, int stock, double price, string name, string desc)
Constructor for Notebook.
Parameters
subjects <int>
stock <int>
price <double>
name <string>
desc <string>
Definition at line 4 of file notebook.cpp.
References Item::setCategory(), setId(), and setSubjects().
Member Function Documentation
getDetails()
string Notebook::getDetails () override virtual
Implements Item::getDetails() for Notebook.
The result is a string of the number of subjects
Implements Item.
Definition at line 12 of file notebook.cpp.
References _subjects.
getSubjects()
int Notebook::getSubjects ()
Get the Notebook's number of subjects.
Returns
<int>
Definition at line 31 of file notebook.cpp.
References _subjects.
setId()
void Notebook::setId () override virtual
Override of Item::setID()
Computes the Notebook's item id by generating the hashes of the class name and the number of subjects and then XOR'ing the hashes.
Implements Item.
Definition at line 21 of file notebook.cpp.
References _subjects, and Item::setId().
Referenced by Notebook().
setSubjects()
void Notebook::setSubjects (int subjects)
Set the number of subjects of the notebook.
Parameters
subjects <int>
Definition at line 29 of file notebook.cpp.
References _subjects.
Referenced by Notebook().
Member Data Documentation
_subjects
int Notebook::_subjects private
Definition at line 54 of file notebook.h.
Referenced by getDetails(), getSubjects(), setId(), and setSubjects().
The documentation for this class was generated from the following files:
src/notebook.h
src/notebook.cpp