Ceid Cpp Project 2020: Item Class Reference
Item Class Reference abstract
Base class for all other items.
#include <item.h>
Public Member Functions
Item (int stock, double price, string name, string desc)
Constructor for Item, called by the derivative classes.
virtual ~Item ()
Virtual destructor to force the reimplementation in the derivatives.
size_t getId ()
Get the ID of the item.
void setStock (int stock)
Set the stock of an item.
int getStock ()
Get the Item's stock.
void setPrice (double price)
Set the price of an item.
double getPrice ()
Get the Item's price.
void setName (string name)
Set the stock of an item.
string getName ()
Get the Item's name.
void setDescription (string desc)
Set the stock of an item.
string getDescription ()
Get the Item's description.
string getCategory ()
Get the Item's category (Pen, Pencil, Paper, Notebook)
string getBasicInfo ()
Get the Item's basic getBasicInfo.
void setId (size_t)
Set the Item's ID based on the hash.
void setCategory (string)
Set the Item's category.
virtual void setId ()=0
Set the Item's ID.
virtual string getDetails ()=0
Get the Item's specialization specific details.
operator std::string ()
Override the cast to std::string operator.
bool operator== (const Item &)
Override for the comparison operator.
Private Attributes
size_t _id = 0
int _stock
double _price
string _name
string _desc
string _category
Friends
ostream & operator<< (ostream &, Item &)
Override for the outstream operator.
Detailed Description
Base class for all other items.
Base abstract class to subclassed by the Pen, Pencil, Paper and Notebook specialized classes. Implements the common functions of setting the common characteristics of items, namely the Name, Stock, Descritpion. Implements getters for common characteristics of items as well as virtual functions that should be re-implemented in each item category.
Definition at line 18 of file item.h.
Constructor & Destructor Documentation
Item()
Item::Item (int stock, double price, string name, string desc)
Constructor for Item, called by the derivative classes.
Parameters
stock <int>.The stock the item should be created with
price <double> The price of the item
name <string> The name of the item, doesn't need to be unique
desc <string> The description of the item
Definition at line 3 of file item.cpp.
References setDescription(), setName(), setPrice(), and setStock().
~Item()
Item::~Item () virtual
Virtual destructor to force the reimplementation in the derivatives.
Definition at line 11 of file item.cpp.
Member Function Documentation
getBasicInfo()
string Item::getBasicInfo ()
Get the Item's basic getBasicInfo.
Returns the common information between items as a commaspace-separated string. The order of the returned inforation is "id, name, price, stock, description"
Returns
<string>
Definition at line 15 of file item.cpp.
References _desc, _id, _name, _price, and _stock.
getCategory()
string Item::getCategory ()
Get the Item's category (Pen, Pencil, Paper, Notebook)
Returns
<string>
Definition at line 52 of file item.cpp.
References _category.
getDescription()
string Item::getDescription ()
Get the Item's description.
Returns
<string>
Definition at line 77 of file item.cpp.
References _desc.
getDetails()
virtual string Item::getDetails () pure virtual
Get the Item's specialization specific details.
Pure abstract function that every derivative should implement. Returns a string of specialization specific details of each Item.
Implemented in Paper, Notebook, Pen, and Pencil.
getId()
size_t Item::getId ()
Get the ID of the item.
The ID of an item is a 4 digit hash generated by the defining characteristics of each item. The hash is computed by each derivative class
Returns
<size_t> The item's hash
Definition at line 57 of file item.cpp.
References _id.
getName()
string Item::getName ()
Get the Item's name.
Returns
<string>
Definition at line 72 of file item.cpp.
References _name.
Referenced by EShop::addItem(), ShoppingCart::addItemOrder(), and ShoppingCart::getItemOrder().
getPrice()
double Item::getPrice ()
Get the Item's price.
Returns
<double>
Definition at line 67 of file item.cpp.
References _price.
getStock()
int Item::getStock ()
Get the Item's stock.
Returns
<int>
Definition at line 62 of file item.cpp.
References _stock.
Referenced by ShoppingCart::addItemOrder(), Buyer::placeOrder(), ShoppingCart::removeItemOrder(), and EShop::updateItemStock().
operator std::string()
Item::operator std::string ()
Override the cast to std::string operator.
Override the cast to string operator to use it to return details about each item. Works by calling the getBasicInfo() and getDetails() functions
Definition at line 31 of file item.cpp.
operator==()
bool Item::operator== (const Item & other)
Override for the comparison operator.
Compares two Item objects by comparing their IDs
Definition at line 44 of file item.cpp.
References _id.
setCategory()
void Item::setCategory (string category)
Set the Item's category.
Set the item's category by removing the first character of the string returned by typeid (In the case of gcc 10 on my machine it is the name of the class prefix by the length of the string (according to the reference it is implementation specific))
Definition at line 50 of file item.cpp.
References _category.
Referenced by Notebook::Notebook(), Paper::Paper(), Pen::Pen(), and Pencil::Pencil().
setDescription()
void Item::setDescription (string desc)
Set the stock of an item.
Parameters
desc <string> The description to set
Definition at line 75 of file item.cpp.
References _desc.
Referenced by Item().
setId() [1/2]
virtual void Item::setId () pure virtual
Set the Item's ID.
Pure abstract function that every derivative should implement. All implementations of this function work on the same way. They create 2 or 3 hashes based on the unique identifiers of each item with are then XOR'd together. The first is identifier is the name of each class as returned by typeid. The second and third (if applicable) are specific to each specialization and documented there.
Implemented in Paper, Notebook, Pen, and Pencil.
Referenced by Paper::setId(), Notebook::setId(), Pen::setId(), and Pencil::setId().
setId() [2/2]
void Item::setId (size_t id)
Set the Item's ID based on the hash.
Provides the common functionality to the derivatives of truncating the hash to a 4 least significant digits. Hopefully they are unique enough to be used as IDs
Definition at line 55 of file item.cpp.
References _id.
setName()
void Item::setName (string name)
Set the stock of an item.
Parameters
name <string> The name to set
Definition at line 70 of file item.cpp.
References _name.
Referenced by Item().
setPrice()
void Item::setPrice (double price)
Set the price of an item.
Parameters
price <double> The price to set
Definition at line 65 of file item.cpp.
References _price.
Referenced by Item().
setStock()
void Item::setStock (int stock)
Set the stock of an item.
Parameters
stock <int> The stock to set
Definition at line 60 of file item.cpp.
References _stock.
Referenced by ShoppingCart::addItemOrder(), Item(), ShoppingCart::removeItemOrder(), and EShop::updateItemStock().
Friends And Related Function Documentation
operator<<
ostream & operator<< (ostream & os, Item & item) friend
Override for the outstream operator.
Used to throw information to the cout garbage can
Definition at line 36 of file item.cpp.
Member Data Documentation
_category
string Item::_category private
Definition at line 178 of file item.h.
Referenced by getCategory(), and setCategory().
_desc
string Item::_desc private
Definition at line 177 of file item.h.
Referenced by getBasicInfo(), getDescription(), and setDescription().
_id
size_t Item::_id = 0 private
Definition at line 173 of file item.h.
Referenced by getBasicInfo(), getId(), operator==(), and setId().
_name
string Item::_name private
Definition at line 176 of file item.h.
Referenced by getBasicInfo(), getName(), and setName().
_price
double Item::_price private
Definition at line 175 of file item.h.
Referenced by getBasicInfo(), getPrice(), and setPrice().
_stock
int Item::_stock private
Definition at line 174 of file item.h.
Referenced by getBasicInfo(), getStock(), and setStock().
The documentation for this class was generated from the following files:
src/item.h
src/item.cpp