Ceid Cpp Project 2020: EShopError Class Reference
EShopError Class Reference
Exception class for passing error messages on failures.
#include <eshoperror.h>
Public Member Functions
EShopError ()
Constructor for empty exception messages.
EShopError (string &&error)
Constructor for empty exception messages.
const string & error () const
Return the error message.
Private Attributes
string _error
Detailed Description
Exception class for passing error messages on failures.
Definition at line 12 of file eshoperror.h.
Constructor & Destructor Documentation
EShopError() [1/2]
EShopError::EShopError () inline
Constructor for empty exception messages.
Definition at line 19 of file eshoperror.h.
EShopError() [2/2]
EShopError::EShopError (string && error) inline
Constructor for empty exception messages.
Parameters
error The error message to pass
Definition at line 25 of file eshoperror.h.
Member Function Documentation
error()
const string & EShopError::error () const inline
Return the error message.
Definition at line 30 of file eshoperror.h.
References _error.
Referenced by main(), Buyer::placeOrder(), Buyer::showCart(), Menu::showCartMenu(), Menu::showLoginMenu(), and Menu::showStatusMenu().
Member Data Documentation
_error
string EShopError::_error private
Definition at line 35 of file eshoperror.h.
Referenced by error().
The documentation for this class was generated from the following file:
src/eshoperror.h