Ceid Cpp Project 2020: Menu Class Reference
Menu Class Reference
Creates a menu for the e-shop's interface.
#include <menu.h>
Public Member Functions
Menu (EShop *)
~Menu ()
void showWelcome ()
void showLoginMenu ()
void showOwnerMenu ()
void showBuyerMenu ()
void showBrowseMenu ()
void showCategoryMenu (string)
void showProductMenu (string, int)
void showCartMenu ()
void showStatusMenu ()
void showCheckoutMenu ()
Private Member Functions
void login (string)
User authentication.
bool askYesNo (string)
Helper function to encapsulate yes/no questions.
Private Attributes
User * _user = nullptr
Owner * _owner = nullptr
Buyer * _buyer = nullptr
EShop * _eshop
Detailed Description
Creates a menu for the e-shop's interface.
This class provides the majority of user input and output. It takes an instantiated EShop and provides a navigation Menu.
Definition at line 20 of file menu.h.
Constructor & Destructor Documentation
Menu()
Menu::Menu (EShop * eshop)
Definition at line 6 of file menu.cpp.
References _eshop, and showWelcome().
~Menu()
Menu::~Menu ()
Definition at line 320 of file menu.cpp.
Member Function Documentation
askYesNo()
bool Menu::askYesNo (string message) private
Helper function to encapsulate yes/no questions.
Definition at line 344 of file menu.cpp.
Referenced by showProductMenu(), and showStatusMenu().
login()
void Menu::login (string email) private
User authentication.
Definition at line 325 of file menu.cpp.
References _buyer, _eshop, _owner, _user, EShop::getBuyerByEmail(), User::getEmail(), User::getName(), and EShop::getOwner().
Referenced by showLoginMenu().
showBrowseMenu()
void Menu::showBrowseMenu ()
Definition at line 153 of file menu.cpp.
References _eshop, _user, EShop::getCategories(), User::isAdmin(), showBuyerMenu(), showCategoryMenu(), and showOwnerMenu().
Referenced by showBuyerMenu(), showCategoryMenu(), and showOwnerMenu().
showBuyerMenu()
void Menu::showBuyerMenu ()
Definition at line 112 of file menu.cpp.
References _buyer, Buyer::getBonus(), Buyer::getCategoryName(), User::getEmail(), User::getName(), showBrowseMenu(), showBuyerMenu(), showCartMenu(), showCheckoutMenu(), and showWelcome().
Referenced by showBrowseMenu(), showBuyerMenu(), showCartMenu(), showCheckoutMenu(), showOwnerMenu(), and showWelcome().
showCartMenu()
void Menu::showCartMenu ()
Definition at line 228 of file menu.cpp.
References _buyer, _eshop, Buyer::checkout(), Buyer::clearCart(), EShopError::error(), EShop::getItemById(), Buyer::getItemOrder(), Buyer::placeOrder(), Buyer::removeFromOrder(), showBuyerMenu(), Buyer::showCart(), and showCartMenu().
Referenced by showBuyerMenu(), and showCartMenu().
showCategoryMenu()
void Menu::showCategoryMenu (string category)
Definition at line 181 of file menu.cpp.
References _eshop, EShop::getProductsInCategory(), showBrowseMenu(), and showProductMenu().
Referenced by showBrowseMenu(), and showProductMenu().
showCheckoutMenu()
void Menu::showCheckoutMenu ()
Definition at line 314 of file menu.cpp.
References _buyer, Buyer::checkout(), and showBuyerMenu().
Referenced by showBuyerMenu().
showLoginMenu()
void Menu::showLoginMenu ()
Definition at line 25 of file menu.cpp.
References EShopError::error(), and login().
Referenced by showWelcome().
showOwnerMenu()
void Menu::showOwnerMenu ()
Definition at line 39 of file menu.cpp.
References _eshop, _owner, User::getEmail(), EShop::getName(), User::getName(), showBrowseMenu(), showBuyerMenu(), showStatusMenu(), and showWelcome().
Referenced by showBrowseMenu(), showStatusMenu(), and showWelcome().
showProductMenu()
void Menu::showProductMenu (string back, int id)
Definition at line 206 of file menu.cpp.
References _buyer, _eshop, _user, askYesNo(), EShop::getItemById(), User::isAdmin(), Buyer::placeOrder(), showCategoryMenu(), EShop::showProduct(), and EShop::updateItemStock().
Referenced by showCategoryMenu().
showStatusMenu()
void Menu::showStatusMenu ()
Definition at line 77 of file menu.cpp.
References _eshop, askYesNo(), EShop::checkStatus(), EShopError::error(), EShop::getBuyerByEmail(), EShop::removeBuyer(), Buyer::showCart(), showOwnerMenu(), and showStatusMenu().
Referenced by showOwnerMenu(), and showStatusMenu().
showWelcome()
void Menu::showWelcome ()
Definition at line 13 of file menu.cpp.
References _eshop, _user, User::isAdmin(), showBuyerMenu(), showLoginMenu(), and showOwnerMenu().
Referenced by Menu(), showBuyerMenu(), and showOwnerMenu().
Member Data Documentation
_buyer
Buyer* Menu::_buyer = nullptr private
Definition at line 47 of file menu.h.
Referenced by login(), showBuyerMenu(), showCartMenu(), showCheckoutMenu(), and showProductMenu().
_eshop
EShop* Menu::_eshop private
Definition at line 48 of file menu.h.
Referenced by login(), Menu(), showBrowseMenu(), showCartMenu(), showCategoryMenu(), showOwnerMenu(), showProductMenu(), showStatusMenu(), and showWelcome().
_owner
Owner* Menu::_owner = nullptr private
Definition at line 46 of file menu.h.
Referenced by login(), and showOwnerMenu().
_user
User* Menu::_user = nullptr private
Definition at line 45 of file menu.h.
Referenced by login(), showBrowseMenu(), showProductMenu(), and showWelcome().
The documentation for this class was generated from the following files:
src/menu.h
src/menu.cpp