Ceid Cpp Project 2020: Pencil Class Reference
Pencil Class Reference final
Class representing a Pencil.
#include <pencil.h>
Public Types
enum Type { H , B , HB }
Enumaration of Pencil types.
Public Member Functions
Pencil (double tipSize, Type type, int stock, double price, string name, string desc)
Constructor for Pencil.
void setTipSize (double tipSize)
Set the tip size of the Pencil.
double getTipSize ()
Get the tip size of the Pencil.
void setType (Type type)
Set the type of the Pencil.
Type getType ()
Get the color of the Pen.
void setId () override
Override of Item::setID()
string getDetails () override
Implements Item::getDetails() for Pen.
Public Member Functions inherited from Item
Item (int stock, double price, string name, string desc)
Constructor for Item, called by the derivative classes.
virtual ~Item ()
Virtual destructor to force the reimplementation in the derivatives.
size_t getId ()
Get the ID of the item.
void setStock (int stock)
Set the stock of an item.
int getStock ()
Get the Item's stock.
void setPrice (double price)
Set the price of an item.
double getPrice ()
Get the Item's price.
void setName (string name)
Set the stock of an item.
string getName ()
Get the Item's name.
void setDescription (string desc)
Set the stock of an item.
string getDescription ()
Get the Item's description.
string getCategory ()
Get the Item's category (Pen, Pencil, Paper, Notebook)
string getBasicInfo ()
Get the Item's basic getBasicInfo.
void setId (size_t)
Set the Item's ID based on the hash.
void setCategory (string)
Set the Item's category.
operator std::string ()
Override the cast to std::string operator.
bool operator== (const Item &)
Override for the comparison operator.
Private Attributes
double _tipSize
Type _type
map< Type, string > _typeMap { {H, "H"}, { B, "B" }, {HB, "HB" } }
Map of Pencil::Type to string representations.
Detailed Description
Class representing a Pencil.
Definition at line 11 of file pencil.h.
Member Enumeration Documentation
Type
enum Pencil::Type
Enumaration of Pencil types.
Enumerator
H
B
HB
Definition at line 18 of file pencil.h.
Constructor & Destructor Documentation
Pencil()
Pencil::Pencil (double tipSize, Pencil::Type type, int stock, double price, string name, string desc)
Constructor for Pencil.
Parameters
tipSize <double>
type <Pencil::Type>
stock <int>
price <double>
name <string>
desc <string>
Definition at line 4 of file pencil.cpp.
References Item::setCategory(), setId(), setTipSize(), and setType().
Member Function Documentation
getDetails()
string Pencil::getDetails () override virtual
Implements Item::getDetails() for Pen.
The result is a commaspace-separated string in the order of "tip size, type"
Implements Item.
Definition at line 22 of file pencil.cpp.
References _tipSize, _type, and _typeMap.
getTipSize()
double Pencil::getTipSize ()
Get the tip size of the Pencil.
Returns
<double>
Definition at line 35 of file pencil.cpp.
References _tipSize.
getType()
Pencil::Type Pencil::getType ()
Get the color of the Pen.
Returns
<Pencil::Type>
Definition at line 40 of file pencil.cpp.
References _type.
setId()
void Pencil::setId () override virtual
Override of Item::setID()
Computes the Pencil's item ID by generating the hashes of the class name, the tip size and the type and then XOR'ing the hashes.
Implements Item.
Definition at line 13 of file pencil.cpp.
References _tipSize, _type, _typeMap, and Item::setId().
Referenced by Pencil().
setTipSize()
void Pencil::setTipSize (double tipSize)
Set the tip size of the Pencil.
Parameters
tipSize <double>
Definition at line 33 of file pencil.cpp.
References _tipSize.
Referenced by Pencil().
setType()
void Pencil::setType (Type type)
Set the type of the Pencil.
Parameters
color <Pencil::Type>
Definition at line 38 of file pencil.cpp.
References _type.
Referenced by Pencil().
Member Data Documentation
_tipSize
double Pencil::_tipSize private
Definition at line 78 of file pencil.h.
Referenced by getDetails(), getTipSize(), setId(), and setTipSize().
_type
Type Pencil::_type private
Definition at line 79 of file pencil.h.
Referenced by getDetails(), getType(), setId(), and setType().
_typeMap
map<Type, string> Pencil::_typeMap { {H, "H"}, { B, "B" }, {HB, "HB" } } private
Map of Pencil::Type to string representations.
Definition at line 81 of file pencil.h.
Referenced by getDetails(), and setId().
The documentation for this class was generated from the following files:
src/pencil.h
src/pencil.cpp