Ceid Cpp Project 2020: Paper Class Reference
Paper Class Reference final
Class representing a Paper.
#include <paper.h>
Public Member Functions
Paper (int pages, int weight, int stock, double price, string name, string desc)
Constructor for Paper.
void setPages (int pages)
Set the pages of Paper.
int getPages ()
Get the pages of Paper.
void setWeight (int)
Set the weight of Paper.
int getWeight ()
Get the weight of Paper.
void setId ()
Override of Item::setID()
string getDetails ()
Implements Item::getDetails() for Paper.
Public Member Functions inherited from Item
Item (int stock, double price, string name, string desc)
Constructor for Item, called by the derivative classes.
virtual ~Item ()
Virtual destructor to force the reimplementation in the derivatives.
size_t getId ()
Get the ID of the item.
void setStock (int stock)
Set the stock of an item.
int getStock ()
Get the Item's stock.
void setPrice (double price)
Set the price of an item.
double getPrice ()
Get the Item's price.
void setName (string name)
Set the stock of an item.
string getName ()
Get the Item's name.
void setDescription (string desc)
Set the stock of an item.
string getDescription ()
Get the Item's description.
string getCategory ()
Get the Item's category (Pen, Pencil, Paper, Notebook)
string getBasicInfo ()
Get the Item's basic getBasicInfo.
void setId (size_t)
Set the Item's ID based on the hash.
void setCategory (string)
Set the Item's category.
operator std::string ()
Override the cast to std::string operator.
bool operator== (const Item &)
Override for the comparison operator.
Private Attributes
int _pages
int _weight
Detailed Description
Class representing a Paper.
Definition at line 12 of file paper.h.
Constructor & Destructor Documentation
Paper()
Paper::Paper (int pages, int weight, int stock, double price, string name, string desc)
Constructor for Paper.
Parameters
int <pages>
int <weight>
int <stock>
double <price>
string <name>
string <desc>
Definition at line 5 of file paper.cpp.
References Item::setCategory(), setId(), setPages(), and setWeight().
Member Function Documentation
getDetails()
string Paper::getDetails () virtual
Implements Item::getDetails() for Paper.
The result is a commaspace-separated string in the order of "pages, weight"
Implements Item.
Definition at line 13 of file paper.cpp.
References _pages, and _weight.
getPages()
int Paper::getPages ()
Get the pages of Paper.
Returns
<int>
Definition at line 34 of file paper.cpp.
References _pages.
getWeight()
int Paper::getWeight ()
Get the weight of Paper.
Returns
<int>
Definition at line 39 of file paper.cpp.
References _weight.
setId()
void Paper::setId () virtual
Override of Item::setID()
Computes the Paper's item ID by generating the hashes of the class name, the number of pages and the weight and then XOR'ing the hashes.
Implements Item.
Definition at line 23 of file paper.cpp.
References _pages, _weight, and Item::setId().
Referenced by Paper().
setPages()
void Paper::setPages (int pages)
Set the pages of Paper.
Parameters
pages <int>
Definition at line 32 of file paper.cpp.
References _pages.
Referenced by Paper().
setWeight()
void Paper::setWeight (int weight)
Set the weight of Paper.
Parameters
subjects <int>
Definition at line 37 of file paper.cpp.
References _weight.
Referenced by Paper().
Member Data Documentation
_pages
int Paper::_pages private
Definition at line 69 of file paper.h.
Referenced by getDetails(), getPages(), setId(), and setPages().
_weight
int Paper::_weight private
Definition at line 70 of file paper.h.
Referenced by getDetails(), getWeight(), setId(), and setWeight().
The documentation for this class was generated from the following files:
src/paper.h
src/paper.cpp