Ceid Cpp Project 2020: Pen Class Reference
Pen Class Reference final
Class representing a Pen.
#include <pen.h>
Public Member Functions
Pen (double tipSize, string color, int stock, double price, string name, string desc)
Constructor for Pen.
void setTipSize (double tipSize)
Set the tip size of the Pen.
double getTipSize ()
Get the tip size of the Pen.
void setColor (string color)
Set the color of the Pen.
string getColor ()
Get the color of the Pen.
void setId () override
Override of Item::setID()
string getDetails () override
Implements Item::getDetails() for Pen.
Public Member Functions inherited from Item
Item (int stock, double price, string name, string desc)
Constructor for Item, called by the derivative classes.
virtual ~Item ()
Virtual destructor to force the reimplementation in the derivatives.
size_t getId ()
Get the ID of the item.
void setStock (int stock)
Set the stock of an item.
int getStock ()
Get the Item's stock.
void setPrice (double price)
Set the price of an item.
double getPrice ()
Get the Item's price.
void setName (string name)
Set the stock of an item.
string getName ()
Get the Item's name.
void setDescription (string desc)
Set the stock of an item.
string getDescription ()
Get the Item's description.
string getCategory ()
Get the Item's category (Pen, Pencil, Paper, Notebook)
string getBasicInfo ()
Get the Item's basic getBasicInfo.
void setId (size_t)
Set the Item's ID based on the hash.
void setCategory (string)
Set the Item's category.
operator std::string ()
Override the cast to std::string operator.
bool operator== (const Item &)
Override for the comparison operator.
Private Attributes
double _tipSize
string _color
Detailed Description
Class representing a Pen.
Definition at line 12 of file pen.h.
Constructor & Destructor Documentation
Pen()
Pen::Pen (double tipSize, string color, int stock, double price, string name, string desc)
Constructor for Pen.
Parameters
tipSize <double>
color <string>
stock <int>
price <double>
name <string>
desc <string>
Definition at line 4 of file pen.cpp.
References Item::setCategory(), setColor(), setId(), and setTipSize().
Member Function Documentation
getColor()
string Pen::getColor ()
Get the color of the Pen.
Returns
<string>
Definition at line 40 of file pen.cpp.
References _color.
getDetails()
string Pen::getDetails () override virtual
Implements Item::getDetails() for Pen.
The result is a commaspace-separated string in the order of "tip size, color"
Implements Item.
Definition at line 22 of file pen.cpp.
References _color, and _tipSize.
getTipSize()
double Pen::getTipSize ()
Get the tip size of the Pen.
Returns
<double>
Definition at line 35 of file pen.cpp.
References _tipSize.
setColor()
void Pen::setColor (string color)
Set the color of the Pen.
Parameters
color <string>
Definition at line 38 of file pen.cpp.
References _color.
Referenced by Pen().
setId()
void Pen::setId () override virtual
Override of Item::setID()
Computes the Pen's item ID by generating the hashes of the class name, the tipSize and the color and then XOR'ing the hashes.
Implements Item.
Definition at line 13 of file pen.cpp.
References _color, _tipSize, and Item::setId().
Referenced by Pen().
setTipSize()
void Pen::setTipSize (double tipSize)
Set the tip size of the Pen.
Parameters
tipSize <double>
Definition at line 33 of file pen.cpp.
References _tipSize.
Referenced by Pen().
Member Data Documentation
_color
string Pen::_color private
Definition at line 70 of file pen.h.
Referenced by getColor(), getDetails(), setColor(), and setId().
_tipSize
double Pen::_tipSize private
Definition at line 69 of file pen.h.
Referenced by getDetails(), getTipSize(), setId(), and setTipSize().
The documentation for this class was generated from the following files:
src/pen.h
src/pen.cpp