Ceid Cpp Project 2020: ShoppingCart Class Reference
ShoppingCart Class Reference
Class implementing the shopping cart.
#include <shoppingcart.h>
Public Member Functions
ShoppingCart (Buyer *buyer)
Constructor for ShoppingCart.
void addItemOrder (Item *item, int quantity)
Add quantity of an Item to the cart.
void removeItemOrder (Item *item)
Remove an item from the cart completely.
void changeItemOrderQuantity (Item *item, int quantity)
Changes the quantity of an item in the cart.
pair< Item *, int > getItemOrder (Item *)
Get the order information of an item in the cart.
set< int > showCart ()
Show the contents of the cart.
void clearCart ()
Clears the cart.
void checkout ()
Performs the checkout.
double calculateNet ()
Calculates the cost of the order.
double calculateCourier ()
Calculates the cost of the courier.
Private Attributes
map< Item *, int > _order
The cart represented as a map.
Buyer * _buyer
The Buyer this cart belongs to.
Detailed Description
Class implementing the shopping cart.
This class implements the shopping cart related functionality. This class is instantiated for each buyer, and requires to access functionality related to that specific buyer. To satisfy that need we pass a pointer to the constructing buyer during instantiation for later use. The cart is represented as a map between the Item and an integer representing the quantity of Item in the cart.
Definition at line 22 of file shoppingcart.h.
Constructor & Destructor Documentation
ShoppingCart()
ShoppingCart::ShoppingCart (Buyer * buyer) explicit
Constructor for ShoppingCart.
Parameters
buyer <Buyer*> Pointer to the buyer owning this cart
Definition at line 5 of file shoppingcart.cpp.
References _buyer.
Member Function Documentation
addItemOrder()
void ShoppingCart::addItemOrder (Item * item, int quantity)
Add quantity of an Item to the cart.
This function also check if the Item is already in the cart, if it is it updates the quantity by adding the requested quantity. It also checks if there is enough stock, if it doesn't, it throws and EShopError exception to be caught by the caller.
Parameters
item <Item*> Reference to an item in the eshop
quantity <int> The quantity of the item
Definition at line 11 of file shoppingcart.cpp.
References _order, changeItemOrderQuantity(), Item::getName(), Item::getStock(), and Item::setStock().
Referenced by Buyer::placeOrder().
calculateCourier()
double ShoppingCart::calculateCourier ()
Calculates the cost of the courier.
It also takes into account the category of the buyer.
Definition at line 61 of file shoppingcart.cpp.
References _buyer, calculateNet(), Buyer::getCategory(), Buyer::Gold, and Buyer::Silver.
Referenced by showCart().
calculateNet()
double ShoppingCart::calculateNet ()
Calculates the cost of the order.
Definition at line 53 of file shoppingcart.cpp.
References _order.
Referenced by calculateCourier(), checkout(), and showCart().
changeItemOrderQuantity()
void ShoppingCart::changeItemOrderQuantity (Item * item, int quantity)
Changes the quantity of an item in the cart.
Also checks of the resulting quantity is below zero and if it is it removes the Item from the cart.
Parameters
item <Item*> Reference to the Item to be removed.
quantity <int> Quantity to remove.
Definition at line 35 of file shoppingcart.cpp.
References _order, and removeItemOrder().
Referenced by addItemOrder().
checkout()
void ShoppingCart::checkout ()
Performs the checkout.
Performs the checkout, asks the user for confirmation. If it is positive it clears the cart and awards the bonus to the user.
Definition at line 97 of file shoppingcart.cpp.
References _buyer, _order, Buyer::awardBonus(), calculateNet(), and showCart().
Referenced by Buyer::checkout().
clearCart()
void ShoppingCart::clearCart ()
Clears the cart.
It doesn't call removeItemOrder because of the use of an iterator.
Definition at line 89 of file shoppingcart.cpp.
References _order.
Referenced by Buyer::clearCart().
getItemOrder()
pair< Item *, int > ShoppingCart::getItemOrder (Item * item)
Get the order information of an item in the cart.
Returns a pair of Item reference and quantity of the item specified if the item is in the cart.
Parameters
item <Item*> Reference to the Item to be returned.
Returns
<pair<Item*,int>> A pair from the cart.
Definition at line 42 of file shoppingcart.cpp.
References _order, and Item::getName().
Referenced by Buyer::getItemOrder().
removeItemOrder()
void ShoppingCart::removeItemOrder (Item * item)
Remove an item from the cart completely.
Also updates the cart.
Parameters
item <Item*> Reference to the Item to be removed.
Definition at line 26 of file shoppingcart.cpp.
References _order, Item::getStock(), and Item::setStock().
Referenced by changeItemOrderQuantity(), and Buyer::removeFromOrder().
showCart()
set< int > ShoppingCart::showCart ()
Show the contents of the cart.
This function prints the contents of the cart and returns a set of Item IDs of the items in the cart for erroneous input in the menu. It also prints the value of the order and the cost of the courier.
Returns
<set<int>> A set of Item IDs in the cart.
Definition at line 72 of file shoppingcart.cpp.
References _order, calculateCourier(), and calculateNet().
Referenced by checkout(), and Buyer::showCart().
Member Data Documentation
_buyer
Buyer* ShoppingCart::_buyer private
The Buyer this cart belongs to.
Definition at line 114 of file shoppingcart.h.
Referenced by calculateCourier(), checkout(), and ShoppingCart().
_order
map<Item*, int> ShoppingCart::_order private
The cart represented as a map.
Definition at line 112 of file shoppingcart.h.
Referenced by addItemOrder(), calculateNet(), changeItemOrderQuantity(), checkout(), clearCart(), getItemOrder(), removeItemOrder(), and showCart().
The documentation for this class was generated from the following files:
src/shoppingcart.h
src/shoppingcart.cpp