Ceid Cpp Project 2020: Buyer Class Reference
Buyer Class Reference final
Specialization of User. Describes a Buyer.
#include <buyer.h>
Public Types
enum Category { Bronze , Silver , Gold }
Buyer _categories.
Public Member Functions
Buyer (string name, string email)
Constructor of Buyer.
Buyer (const Buyer &)=delete
Disable the copy constructor for buyer.
bool isAdmin ()
Impementation of isAdmin() of User.
void awardBonus (double orderValue)
Set the buyer's bonus based on the cost of the order.
void placeOrder (Item *item, int quantity)
Add an item to the cart with the specified quantity.
void removeFromOrder (Item *item)
Removes an item from the cart completely.
void checkout ()
Wrapper to ShoppingCart::checkout()
set< int > showCart ()
Wrapper to ShoppingCart::showCart()
pair< Item *, int > getItemOrder (Item *)
Wrapper to ShoppingCart::getItemOrder()
void clearCart ()
Wrapper to ShoppingCart::clearCart()
bool operator== (Buyer &)
Comparission operator between two Buyers.
Buyer & operator= (const Buyer &)=delete
Disable the copy operator for buyer.
int getBonus ()
Get the Buyer's bonus.
Category getCategory ()
Get the Buyer's category.
string getCategoryName ()
Get the Buyer's category as string.
Public Member Functions inherited from User
User (string name, string email)
Constructor for User, called by Owner and Buyer.
string getName ()
Get the Name of the user.
string getEmail ()
Get the Email of the user.
Private Member Functions
void setBonus (double)
Sets a buyer's bonus based on the cost.
void setCategory ()
Sets a buyer's category based on _bonus.
Private Attributes
int _bonus
Category _category
map< Category, int > _categoryScore { {Bronze, 0}, {Silver, 100}, {Gold, 200} }
Map of the categories and their respective lower end scores.
map< Category, string > _categoryString { {Bronze, "Bronze"}, {Silver, "Silver"}, {Gold, "Gold"} }
Map of the categories and their string representations.
ShoppingCart * _cart
Pointer to the user's cart (forward declarations and such)
Static Private Attributes
static constexpr initializer_list< Category > _categories = {Bronze, Silver, Gold}
I just needed an iterator over the categories, so yeah...
Detailed Description
Specialization of User. Describes a Buyer.
Derivative class to specialize a User. Implements Buyer related functionality.
Definition at line 21 of file buyer.h.
Member Enumeration Documentation
Category
enum Buyer::Category
Buyer _categories.
Enumeration of the different Buyer status categories. Used to determine the perks of a Buyer.
Enumerator
Bronze
Silver
Gold
Definition at line 44 of file buyer.h.
Constructor & Destructor Documentation
Buyer() [1/2]
Buyer::Buyer (string name, string email)
Constructor of Buyer.
Parameters
name User's name
email User's login email
Definition at line 5 of file buyer.cpp.
References _bonus, _cart, _category, and Bronze.
Buyer() [2/2]
Buyer::Buyer (const Buyer &) delete
Disable the copy constructor for buyer.
Member Function Documentation
awardBonus()
void Buyer::awardBonus (double orderValue)
Set the buyer's bonus based on the cost of the order.
Parameters
orderValue double The value of the order
Definition at line 13 of file buyer.cpp.
References setBonus(), and setCategory().
Referenced by ShoppingCart::checkout().
checkout()
void Buyer::checkout ()
Wrapper to ShoppingCart::checkout()
Definition at line 46 of file buyer.cpp.
References _cart, and ShoppingCart::checkout().
Referenced by Menu::showCartMenu(), and Menu::showCheckoutMenu().
clearCart()
void Buyer::clearCart ()
Wrapper to ShoppingCart::clearCart()
Definition at line 73 of file buyer.cpp.
References _cart, and ShoppingCart::clearCart().
Referenced by Menu::showCartMenu().
getBonus()
int Buyer::getBonus ()
Get the Buyer's bonus.
Definition at line 91 of file buyer.cpp.
References _bonus.
Referenced by Menu::showBuyerMenu().
getCategory()
Buyer::Category Buyer::getCategory ()
Get the Buyer's category.
Definition at line 100 of file buyer.cpp.
References _category.
Referenced by ShoppingCart::calculateCourier().
getCategoryName()
string Buyer::getCategoryName ()
Get the Buyer's category as string.
Definition at line 103 of file buyer.cpp.
References _category, and _categoryString.
Referenced by Menu::showBuyerMenu().
getItemOrder()
pair< Item *, int > Buyer::getItemOrder (Item * item)
Wrapper to ShoppingCart::getItemOrder()
Returns
Returns a pair containing an item pointer and the quantity int in the cart
Definition at line 63 of file buyer.cpp.
References _cart, and ShoppingCart::getItemOrder().
Referenced by Menu::showCartMenu().
isAdmin()
bool Buyer::isAdmin () virtual
Impementation of isAdmin() of User.
Parameters
none
Returns
bool Always false
Implements User.
Definition at line 106 of file buyer.cpp.
operator=()
Buyer & Buyer::operator= (const Buyer &) delete
Disable the copy operator for buyer.
operator==()
bool Buyer::operator== (Buyer & other)
Comparission operator between two Buyers.
Returns
bool True if they have the same name and email otherwise false
Definition at line 80 of file buyer.cpp.
References User::getEmail(), and User::getName().
placeOrder()
void Buyer::placeOrder (Item * item, int quantity)
Add an item to the cart with the specified quantity.
This function checks if the the cart already contains the item. If it does, it updates the quantity in the cart. Also used to remove a quantity using negative values.
Parameters
item Item* The item to add to the cart
quantity int The selected quantity
Definition at line 20 of file buyer.cpp.
References _cart, ShoppingCart::addItemOrder(), EShopError::error(), and Item::getStock().
Referenced by main(), Menu::showCartMenu(), and Menu::showProductMenu().
removeFromOrder()
void Buyer::removeFromOrder (Item * item)
Removes an item from the cart completely.
Parameters
item Item* The item to remove
Definition at line 40 of file buyer.cpp.
References _cart, and ShoppingCart::removeItemOrder().
Referenced by Menu::showCartMenu().
setBonus()
void Buyer::setBonus (double value) private
Sets a buyer's bonus based on the cost.
Definition at line 86 of file buyer.cpp.
References _bonus.
Referenced by awardBonus().
setCategory()
void Buyer::setCategory () private
Sets a buyer's category based on _bonus.
Definition at line 94 of file buyer.cpp.
References _bonus, _categories, _category, and _categoryScore.
Referenced by awardBonus().
showCart()
set< int > Buyer::showCart ()
Wrapper to ShoppingCart::showCart()
Returns
Returns a set of the IDs of the items in the cart
Definition at line 52 of file buyer.cpp.
References _cart, EShopError::error(), and ShoppingCart::showCart().
Referenced by Menu::showCartMenu(), and Menu::showStatusMenu().
Member Data Documentation
_bonus
int Buyer::_bonus private
Definition at line 137 of file buyer.h.
Referenced by Buyer(), getBonus(), setBonus(), and setCategory().
_cart
ShoppingCart* Buyer::_cart private
Pointer to the user's cart (forward declarations and such)
Definition at line 146 of file buyer.h.
Referenced by Buyer(), checkout(), clearCart(), getItemOrder(), placeOrder(), removeFromOrder(), and showCart().
_categories
constexpr initializer_list<Category> Buyer::_categories = {Bronze, Silver, Gold} static constexpr private
I just needed an iterator over the categories, so yeah...
Definition at line 144 of file buyer.h.
Referenced by setCategory().
_category
Category Buyer::_category private
Definition at line 138 of file buyer.h.
Referenced by Buyer(), getCategory(), getCategoryName(), and setCategory().
_categoryScore
map<Category, int> Buyer::_categoryScore { {Bronze, 0}, {Silver, 100}, {Gold, 200} } private
Map of the categories and their respective lower end scores.
Definition at line 140 of file buyer.h.
Referenced by setCategory().
_categoryString
map<Category, string> Buyer::_categoryString { {Bronze, "Bronze"}, {Silver, "Silver"}, {Gold, "Gold"} } private
Map of the categories and their string representations.
Definition at line 142 of file buyer.h.
Referenced by getCategoryName().
The documentation for this class was generated from the following files:
src/buyer.h
src/buyer.cpp